spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.11.48.193:3306/sell?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
#   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
#   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  jpa:
    show-sql: true
  redis:
    host: 10.11.48.193
    port: 6379
#logging:
#  pattern:
#    console: "%d - %msg%n"


wechat:
    mpAppId: wx514cc4048133e1d6


#    mpAppId: wxd898fcb01713c658
    mpAppSecret: e5b2b9cc7549136bc6a5622291a09809
    openAppId: wx6ad144e54af67d87
    openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
    mchId: 1483469312
    mchKey: C5245D70627C1F8E9964D494B0735025
    keyPath: E:/ele-encoding/coding-117/doc/h5.p12
    notifyUrl: http://thexx.natapp1.cc/sell/pay/notify
    templateId:
      orderStatus: LUD2EJnnqd7SnVP3UEtzqVy3_ffGgTLi8Ouog1eCNMY

projectUrl:
    wechatMpAuthorize: http://thexx.natapp1.cc
    wechatOpenAuthorize: http://thexx.natapp1.cc
    sell: http://thexx.natapp1.cc
logging:
  level:
    cn.hust.dataobject.mapper: trace
server:
  servlet:
    context-path: /sell
