spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.11.48.193:3306/sell?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"


wechat:
    mpAppId: wxd898fcb01713c658
    appsecret: e5b2b9cc7549136bc6a5622291a09809
    mchId: 1483469312
    mchKey: C5245D70627C1F8E9964D494B0735025
    keyPath: E:/ele-encoding/coding-117/doc/h5.p12
    notifyUrl: http://thexx.natapp1.cc/sell/pay/notify